#!/bin/sh
if [ -f ".env" ]; then
  set -a
  . ./.env
  set +a
fi

VITE_BACKEND_URL=${VITE_BACKEND_URL:-"http://localhost:9090"}
VITE_CARDANO_NETWORK=${VITE_CARDANO_NETWORK:-"mainnet"}

OUTPUT_DIR=${1:-./public}
cat > "$OUTPUT_DIR/config.json" <<EOF
{
  "_warning": "WARNING: This file is autogenerated by config.sh. Do not edit manually. Changes will be overwritten.",
  "backendUrl": "${VITE_BACKEND_URL}",
  "cardanoNetwork": "${VITE_CARDANO_NETWORK}"
}
EOF