FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

FROM nginx:alpine
RUN apk add --no-cache nodejs npm && \
    cd /opt && npm install dotenv && ln -s /opt/node_modules /

COPY --from=build /app /app
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY config.js /config.js
COPY entrypoint-custom.sh /entrypoint.sh
RUN chmod +x /config.js /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
EXPOSE 80
